import typing as ty

import core.ast_nodes as ast
import core.token_ as tok

TT = tok.TokenTypes


class ParserProtocol(ty.Protocol):
    token: tok.Token
    exprOps: tuple[TT, ...]
    factorOps: tuple[TT, ...]
    termOps: tuple[TT, ...]
    unaryOps: tuple[TT, ...]
    primValidTyps: tuple[TT, ...]

    def nxtTok(self) -> tok.Token: ...
    def chkTok(
        self, typ: TT | None = None, val: ty.Any = None, token: tok.Token | None = None
    ) -> bool: ...
    def chkTokRange(
        self, span: list[int] | tuple[int, int], tokenOrTT: tok.Token | TT | None = None
    ) -> bool: ...
    def peekTok(self, n: int = 1) -> tok.Token: ...
    def isTokPresentInPeek(self, typ: TT | None = None, val: ty.Any = None) -> bool: ...

    # TODO: Remove the following line if needed...
    def skipWSToks(self, exclude: ty.Iterable[TT] = []) -> None: ...
    def skipTillResyncToks(self, typ: TT | list[TT] = TT.DUMMY, val: ty.Any = None) -> None: ...
    def parseCfg(self) -> ast.CfgNode | list[ast.ErrNode]: ...
    def parseStmt(self) -> ast.ASTNode: ...
    def parseBreak(self) -> ast.BreakNode | ast.ErrNode: ...
    def parseConti(self) -> ast.ContiNode | ast.ErrNode: ...
    def parseRet(self) -> ast.RetNode | ast.ErrNode: ...
    def parseCmpndStmt(self) -> ast.StmtNode | ast.ErrNode: ...
    def parseIf(self) -> ast.IfNode | ast.ErrNode: ...
    def parseWhile(self) -> ast.WhileNode | ast.ErrNode: ...
    def parseFn(self) -> ast.FnNode | ast.ErrNode: ...
    def parseLet(self) -> ast.LetNode | ast.ErrNode: ...
    def parsePrn(self) -> ast.PrnNode | ast.ErrNode: ...
    def parseExpr(self) -> ast.GrpNode | ast.ErrNode: ...
    def parseCh(self) -> ast.ChNode | ast.ErrNode: ...
